# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('category', models.CharField(choices=[('ZH', '综合新闻'), ('XT', '新闻头条'), ('XJ', '新闻聚焦'), ('YX', '院系动态'), ('MT', '媒体财大'), ('JB', '讲座报告'), ('TZ', '通知公告'), ('JY', '讲座预告'), ('XY', '校园传真'), ('YX', '影像财大'), ('LD', '领导讲话'), ('LT', '财大论坛'), ('RW', '人物风采'), ('SP', '视频财大')], max_length=4)),
                ('date', models.DateTimeField()),
                ('editor', models.CharField(max_length=31)),
                ('content', models.TextField()),
            ],
        ),
    ]
